import { PDFDocument, StandardFonts, rgb, type PDFFont, type PDFPage } from "pdf-lib";
import QRCode from "qrcode";

/**
 * QR label sheets as PDF (owner decision 3: labels are generated by the
 * system). Server-side only, no external service. The QR code carries only
 * the URL it is given; callers pass an internal URL with an opaque id, so a
 * scan outside the system reveals nothing (ADR 0017).
 */
export interface Label {
  /** Encoded in the QR code. */
  url: string;
  /** Printed code, also used for the manual-entry fallback. */
  code: string;
  lines: string[];
}

export interface LabelSheetOptions {
  title: string;
  footer: string;
}

const A4 = { w: 595.28, h: 841.89 };
const COLS = 3;
const ROWS = 7;
const MARGIN_X = 14;
const MARGIN_Y = 22;
const CELL_W = (A4.w - 2 * MARGIN_X) / COLS;
const CELL_H = (A4.h - 2 * MARGIN_Y) / ROWS;
const QR = 84;

/** Characters the standard PDF fonts (WinAnsi) cannot encode are replaced. */
function safe(text: string): string {
  return text.replace(/[^\x20-\x7e -ÿ]/g, "?");
}

function fit(text: string, font: PDFFont, size: number, max: number): string {
  let t = safe(text);
  if (font.widthOfTextAtSize(t, size) <= max) return t;
  while (t.length > 1 && font.widthOfTextAtSize(`${t}…`, size) > max) t = t.slice(0, -1);
  return `${t}…`;
}

function drawQr(page: PDFPage, url: string, x: number, y: number, size: number) {
  const qr = QRCode.create(url, { errorCorrectionLevel: "M" });
  const n = qr.modules.size;
  const quiet = 2;
  const m = size / (n + 2 * quiet);
  for (let r = 0; r < n; r++) {
    for (let c = 0; c < n; c++) {
      if (qr.modules.get(r, c)) page.drawRectangle({ x: x + (c + quiet) * m, y: y + size - (r + quiet + 1) * m, width: m, height: m, color: rgb(0, 0, 0) });
    }
  }
}

export async function renderLabelSheet(labels: Label[], opts: LabelSheetOptions): Promise<Uint8Array> {
  const doc = await PDFDocument.create();
  doc.setTitle(safe(opts.title));
  doc.setCreator("SK Management");
  doc.setProducer("SK Management");
  const regular = await doc.embedFont(StandardFonts.Helvetica);
  const bold = await doc.embedFont(StandardFonts.HelveticaBold);
  const perPage = COLS * ROWS;
  const pages = Math.max(1, Math.ceil(labels.length / perPage));
  for (let p = 0; p < pages; p++) {
    const page = doc.addPage([A4.w, A4.h]);
    page.drawText(fit(`${opts.title} — ${p + 1}/${pages}`, regular, 7, A4.w - 2 * MARGIN_X), { x: MARGIN_X, y: A4.h - 12, size: 7, font: regular, color: rgb(0.4, 0.4, 0.4) });
    labels.slice(p * perPage, (p + 1) * perPage).forEach((label, i) => {
      const col = i % COLS;
      const row = Math.floor(i / COLS);
      const x = MARGIN_X + col * CELL_W;
      const y = A4.h - MARGIN_Y - (row + 1) * CELL_H;
      page.drawRectangle({ x: x + 2, y: y + 2, width: CELL_W - 4, height: CELL_H - 4, borderColor: rgb(0.75, 0.75, 0.75), borderWidth: 0.5 });
      drawQr(page, label.url, x + 6, y + (CELL_H - QR) / 2, QR);
      const tx = x + QR + 10;
      const tw = CELL_W - QR - 16;
      let ty = y + CELL_H - 26;
      page.drawText(fit(label.code, bold, 12, tw), { x: tx, y: ty, size: 12, font: bold });
      for (const line of label.lines.slice(0, 4)) {
        ty -= 13;
        page.drawText(fit(line, regular, 8.5, tw), { x: tx, y: ty, size: 8.5, font: regular });
      }
      page.drawText(fit(opts.footer, regular, 6, tw), { x: tx, y: y + 10, size: 6, font: regular, color: rgb(0.4, 0.4, 0.4) });
    });
  }
  return doc.save();
}
